Do not add suffix into image_name
sclorg/build-and-push-action pull request #10
Opened 2022-03-30 11:52 UTC by phracek

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

2022-03-30 11:59 UTC, zmiklank requested changes
Hi, thanks for the PR.

However, I would suggest using two separate inputs for "suffix" and "tag".
This approach brings multiple features:
1) is generic - we aim to support also non-sclorg repos in the future
2) allows users to insert multiple tags
3) does not introduce any more conditionals and action steps
4) if it will be released in a version different than v1 we would not need to rewrite existing build-and-push actions in our containers.

Please think about this option.

2022-03-31 08:31 UTC, phracek commented
Good, point, I have updated this pull request. It adds suffix.

2022-04-04 06:27 UTC, zmiklank commented
@phracek, thanks for adjusting the PR.

I have one note, and I am not sure about the proceeding:
In step `check_exclude_file` we check if `.exclude-${{ inputs.tag }}` exists, however, that could be misleading, as logically, excluding mechanism has nothing to do with a tag as it is.

One way we can solve this is that we would check against  `.exclude-${{ inputs.suffix }}` and will let the user know in the description, that this input is used for 2 purposes.
Or we can leave it as it is, but then would be impossible to use more tags for the built image, and also it would be intransparent for the user.

WDYT?

2022-04-04 14:55 UTC, phracek commented
> One way we can solve this is that we would check against `.exclude-${{ inputs.suffix }}` and will let the user know in the description, that this input is used for 2 purposes.
> Or we can leave it as it is, but then would be impossible to use more tags for the built image, and also it would be intransparent for the user.

What about if suffix will be empty?

2022-04-04 18:09 UTC, phracek commented
A great approach would be to add a field like `docker_suffix` which will be used for checking Dockerfiles and .exclude files

2022-04-04 18:09 UTC, phracek commented
This will pull request will add suffix for image_names and the other pull request will add a new field.

2022-04-05 07:50 UTC, zmiklank commented on action.yml
> +    description: 'The action will add suffix to image name'
```suggestion
    description: 'A suffix to the image name. Also used for the excluding mechanism, see README.md'
```
I can adjust the README separately.

2022-04-05 07:52 UTC, zmiklank submitted a review, later dismissed
Agreed, thanks!
I suggested a change in description, but otherwise LGTM.

2022-04-05 12:04 UTC, zmiklank requested changes

2022-04-05 12:04 UTC, zmiklank commented on action.yml
> +    description: 'Suffix name to image name'
```suggestion
    description: 'A suffix for the name of the built image'
```

2022-04-05 12:04 UTC, zmiklank commented on action.yml
> +          # See https://devhints.io/bash
```suggestion
```

I suggest removing this comment, but this suggestion can be ignored.

2022-04-05 12:04 UTC, zmiklank commented on action.yml
> +          suffix='centos7'
Is there any possibility to rename the Dockerfiles for centos7 to `Dockerfile.centos7` in the future? This condition seems to be too sclorg-specific.

However, taking the suffix for the exclude mechanism from the Dockerfile name seems like the best solution to me and this condition is IMO unavoidable in the current situation.
Moreover, the whole exclude mechanism could be considered to be too sclorg-specific, so I would agree with bringing the centos7 condition to the `main` branch.

2022-04-05 12:24 UTC, phracek commented on action.yml
> +          suffix='centos7'
Let's discuss it on our meeting. It make sense to me at all? 
@hhorak @pkubatrh WDYT?

2022-04-05 12:26 UTC, phracek commented on action.yml
> +          suffix='centos7'
I guess, for now, it can leave there and in the future, we can remove it as soon as `Dockerfile` disappears.

2022-04-05 12:30 UTC, zmiklank commented on action.yml
> +          suffix='centos7'
OK, I agree.

And could you please squash the commits before merging?

2022-04-05 12:52 UTC, phracek commented on action.yml
> +          suffix='centos7'
Sure

2022-04-05 12:58 UTC, zmiklank approved these changes

2022-04-05 13:14 UTC, merged