Move release tag from v*.*.* to v1 automaticaly
sclorg/build-and-push-action pull request #12
Opened 2022-04-05 13:41 UTC by phracek

See similar approach which we already have in `testing-farm-as-a-github-action`.
https://github.com/sclorg/testing-farm-as-github-action/blob/main/.github/workflows/publish-release.yml

As soon as the new release is published then the tag is automatically moved into the release tag as @v1.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

2022-04-13 11:03 UTC, zmiklank requested changes
Thank you for PR, please see my comments.

2022-04-13 11:03 UTC, zmiklank commented on .github/workflows/publish-release.yml
> +          fetch-depth: 0
Do we really need this?
From README[1]:
```
    # Number of commits to fetch. 0 indicates all history for all branches and tags.
    # Default: 1
    fetch-depth: ''
```
[1] https://github.com/actions/checkout

2022-04-13 11:03 UTC, zmiklank commented on .github/workflows/publish-release.yml
> +          git push origin refs/tags/v${{ steps.version.outputs.major }} -f
It seems, that this action moves the tag to the last used **major** version, not always to **v1**.
Please adjust the commit message, if this statement is correct.

2022-04-28 09:05 UTC, phracek commented on .github/workflows/publish-release.yml
> +          fetch-depth: 0
It is not needed.

2022-05-31 14:35 UTC, merged